spring:
  #  datasource:
  #    url: jdbc:mysql://
  #    username:
  #    password:
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 886910088587-o9m46l419mn0kc22hogkpsruft1bvqs2.apps.googleusercontent.com
            client-secret: kciTx4Su5qCQfpuMShaafUrP

custom:
  oauth2:
    kakao:
      client-id: f3e6ab8a859317e156733a7b55b224b1

#kakao:
#  client:
#    clientId : f3e6ab8a859317e156733a7b55b224b1
#    accessTokenUri : https://kauth.kakao.com/oauth/token
#    userAuthorizationUri : https://kauth.kakao.com/oauth/auuthorize
#  resource:
#    userInfoUri : https://kapi.kakao.com/v1/user/me

